name: 'Build'
on:
  push:
    branches: [ bleeding-edge, mainline ]
    paths:
      - '.github/workflows/*.yml'
      - '**.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
  create:
    tags:
      - v*
  workflow_dispatch:
jobs:
  push:
    strategy:
      matrix:
        variant:
          - tier-1
          - tier-2
          #- tier-3
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            alphanecron/igloo
          tags: |
            type=ref,event=pr,prefix=pr-,suffix=suffix=-${{ matrix.variant }}
            type=pep440,pattern={{version}},suffix=-${{ matrix.variant }}
            type=raw,${{ matrix.variant }}
            type=sha,prefix=,suffix=_${{ matrix.variant }}
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          target: ${{ matrix.variant }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
