name: 'Build'
on:
  push:
    branches: [ bleeding-edge, mainline ]
    paths:
      - 'polar/**.go'
      - 'main.go'
      - 'go.mod'
      - 'go.sum'
      - 'Dockerfile'
      - 'docker-compose.yml'
  create:
    tags:
      - v*
  workflow_dispatch:
jobs:
  push:
    name: Push to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v4
        with:
          repository: alphanecron/polar
          dockerfile: Dockerfile
          push: true
          tag_with_ref: true
